// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pos/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_pos/core/common/result.dart' as _i6;
import 'package:flutter_pos/data/datasources/remote/auth_remote_datasource_impl.dart'
    as _i4;
import 'package:flutter_pos/data/models/user_model.dart' as _i7;
import 'package:flutter_pos/domain/entities/user_entity.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSupabaseClient_0 extends _i1.SmartFake
    implements _i2.SupabaseClient {
  _FakeSupabaseClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceImpl extends _i1.Mock
    implements _i4.AuthRemoteDataSourceImpl {
  MockAuthRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SupabaseClient get supabaseClient =>
      (super.noSuchMethod(
            Invocation.getter(#supabaseClient),
            returnValue: _FakeSupabaseClient_0(
              this,
              Invocation.getter(#supabaseClient),
            ),
          )
          as _i2.SupabaseClient);

  @override
  _i5.Future<_i6.Result<_i7.UserModel>> signInWithEmailAndPassword(
    String? subdomain,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [
              subdomain,
              email,
              password,
            ]),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  subdomain,
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel>>);

  @override
  _i5.Future<_i6.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.UserModel?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel?>>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel?>>);
}

/// A class which mocks [UserModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserModel extends _i1.Mock implements _i7.UserModel {
  MockUserModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  set id(String? _id) => super.noSuchMethod(
    Invocation.setter(#id, _id),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? _email) => super.noSuchMethod(
    Invocation.setter(#email, _email),
    returnValueForMissingStub: null,
  );

  @override
  set phone(String? _phone) => super.noSuchMethod(
    Invocation.setter(#phone, _phone),
    returnValueForMissingStub: null,
  );

  @override
  set name(String? _name) => super.noSuchMethod(
    Invocation.setter(#name, _name),
    returnValueForMissingStub: null,
  );

  @override
  set gender(String? _gender) => super.noSuchMethod(
    Invocation.setter(#gender, _gender),
    returnValueForMissingStub: null,
  );

  @override
  set birthdate(String? _birthdate) => super.noSuchMethod(
    Invocation.setter(#birthdate, _birthdate),
    returnValueForMissingStub: null,
  );

  @override
  set imageUrl(String? _imageUrl) => super.noSuchMethod(
    Invocation.setter(#imageUrl, _imageUrl),
    returnValueForMissingStub: null,
  );

  @override
  set authProvider(String? _authProvider) => super.noSuchMethod(
    Invocation.setter(#authProvider, _authProvider),
    returnValueForMissingStub: null,
  );

  @override
  set createdAt(String? _createdAt) => super.noSuchMethod(
    Invocation.setter(#createdAt, _createdAt),
    returnValueForMissingStub: null,
  );

  @override
  set updatedAt(String? _updatedAt) => super.noSuchMethod(
    Invocation.setter(#updatedAt, _updatedAt),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.UserEntity toEntity() =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, []),
            returnValue: _FakeUserEntity_1(
              this,
              Invocation.method(#toEntity, []),
            ),
          )
          as _i3.UserEntity);
}

/// A class which mocks [UserEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserEntity extends _i1.Mock implements _i3.UserEntity {
  MockUserEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);

  @override
  _i3.UserEntity copyWith({
    String? id,
    String? phone,
    String? email,
    String? name,
    String? gender,
    String? birthdate,
    String? imageUrl,
    _i3.AuthProvider? authProvider,
    String? createdAt,
    String? updatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #phone: phone,
              #email: email,
              #name: name,
              #gender: gender,
              #birthdate: birthdate,
              #imageUrl: imageUrl,
              #authProvider: authProvider,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
            }),
            returnValue: _FakeUserEntity_1(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #phone: phone,
                #email: email,
                #name: name,
                #gender: gender,
                #birthdate: birthdate,
                #imageUrl: imageUrl,
                #authProvider: authProvider,
                #createdAt: createdAt,
                #updatedAt: updatedAt,
              }),
            ),
          )
          as _i3.UserEntity);
}
