// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_pos/test/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_pos/core/common/result.dart' as _i7;
import 'package:flutter_pos/core/services/connectivity/ping_service.dart'
    as _i2;
import 'package:flutter_pos/core/services/network/api_client.dart' as _i3;
import 'package:flutter_pos/data/datasources/local/product_local_datasource_impl.dart'
    as _i6;
import 'package:flutter_pos/data/datasources/local/queued_action_local_datasource_impl.dart'
    as _i11;
import 'package:flutter_pos/data/datasources/remote/product_remote_datasource_impl.dart'
    as _i10;
import 'package:flutter_pos/data/models/product_model.dart' as _i8;
import 'package:flutter_pos/data/models/queued_action_model.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePingData_0 extends _i1.SmartFake implements _i2.PingData {
  _FakePingData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiClient_1 extends _i1.SmartFake implements _i3.ApiClient {
  _FakeApiClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPingService extends _i1.Mock implements _i2.PingService {
  MockPingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i5.Future<void> startPing({
    String? host = '8.8.8.8',
    int? count,
    int? interval = 1,
    int? maxPingLatencyTolerance = 400,
    int? pingLatencyToleranceCount = 3,
    int? maxLines = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startPing, [], {
              #host: host,
              #count: count,
              #interval: interval,
              #maxPingLatencyTolerance: maxPingLatencyTolerance,
              #pingLatencyToleranceCount: pingLatencyToleranceCount,
              #maxLines: maxLines,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(dynamic Function(List<int>, List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(#addListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(dynamic Function(List<int>, List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void clearListeners() => super.noSuchMethod(
    Invocation.method(#clearListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void addConnectionStatusListener(dynamic Function(bool)? listener) =>
      super.noSuchMethod(
        Invocation.method(#addConnectionStatusListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void removeConnectionStatusListener(dynamic Function(bool)? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeConnectionStatusListener, [listener]),
        returnValueForMissingStub: null,
      );

  @override
  void clearConnectionStatusListeners() => super.noSuchMethod(
    Invocation.method(#clearConnectionStatusListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopPing() => super.noSuchMethod(
    Invocation.method(#stopPing, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.PingData parsePingLine(String? line) =>
      (super.noSuchMethod(
            Invocation.method(#parsePingLine, [line]),
            returnValue: _FakePingData_0(
              this,
              Invocation.method(#parsePingLine, [line]),
            ),
          )
          as _i2.PingData);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProductLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDatasourceImpl extends _i1.Mock
    implements _i6.ProductLocalDatasourceImpl {
  MockProductLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.Result<int>> createProduct(_i8.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i5.Future<_i7.Result<int>>.value(
              _i9.dummyValue<_i7.Result<int>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<int>>);

  @override
  _i5.Future<_i7.Result<void>> updateProduct(_i8.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<void>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<_i8.ProductModel?>> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i5.Future<_i7.Result<_i8.ProductModel?>>.value(
              _i9.dummyValue<_i7.Result<_i8.ProductModel?>>(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<_i8.ProductModel?>>);

  @override
  _i5.Future<_i7.Result<List<_i8.ProductModel>>> getAllUserProducts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserProducts, [userId]),
            returnValue: _i5.Future<_i7.Result<List<_i8.ProductModel>>>.value(
              _i9.dummyValue<_i7.Result<List<_i8.ProductModel>>>(
                this,
                Invocation.method(#getAllUserProducts, [userId]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<List<_i8.ProductModel>>>);

  @override
  _i5.Future<_i7.Result<List<_i8.ProductModel>>> getUserProducts(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserProducts,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i5.Future<_i7.Result<List<_i8.ProductModel>>>.value(
              _i9.dummyValue<_i7.Result<List<_i8.ProductModel>>>(
                this,
                Invocation.method(
                  #getUserProducts,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i7.Result<List<_i8.ProductModel>>>);
}

/// A class which mocks [ProductRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDatasourceImpl extends _i1.Mock
    implements _i10.ProductRemoteDatasourceImpl {
  MockProductRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_1(this, Invocation.getter(#apiClient)),
          )
          as _i3.ApiClient);

  @override
  _i4.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_2(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i4.SharedPreferences);

  @override
  String get shopId =>
      (super.noSuchMethod(
            Invocation.getter(#shopId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#shopId),
            ),
          )
          as String);

  @override
  _i5.Future<_i7.Result<int>> createProduct(_i8.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i5.Future<_i7.Result<int>>.value(
              _i9.dummyValue<_i7.Result<int>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<int>>);

  @override
  _i5.Future<_i7.Result<void>> updateProduct(_i8.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<void>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<_i8.ProductModel?>> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i5.Future<_i7.Result<_i8.ProductModel?>>.value(
              _i9.dummyValue<_i7.Result<_i8.ProductModel?>>(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<_i8.ProductModel?>>);

  @override
  _i5.Future<_i7.Result<List<_i8.ProductModel>>> getAllUserProducts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserProducts, [userId]),
            returnValue: _i5.Future<_i7.Result<List<_i8.ProductModel>>>.value(
              _i9.dummyValue<_i7.Result<List<_i8.ProductModel>>>(
                this,
                Invocation.method(#getAllUserProducts, [userId]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<List<_i8.ProductModel>>>);

  @override
  _i5.Future<_i7.Result<List<_i8.ProductModel>>> getUserProducts(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserProducts,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i5.Future<_i7.Result<List<_i8.ProductModel>>>.value(
              _i9.dummyValue<_i7.Result<List<_i8.ProductModel>>>(
                this,
                Invocation.method(
                  #getUserProducts,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i7.Result<List<_i8.ProductModel>>>);
}

/// A class which mocks [QueuedActionLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueuedActionLocalDatasourceImpl extends _i1.Mock
    implements _i11.QueuedActionLocalDatasourceImpl {
  MockQueuedActionLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.Result<int>> createQueuedAction(
    _i12.QueuedActionModel? queue,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createQueuedAction, [queue]),
            returnValue: _i5.Future<_i7.Result<int>>.value(
              _i9.dummyValue<_i7.Result<int>>(
                this,
                Invocation.method(#createQueuedAction, [queue]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<int>>);

  @override
  _i5.Future<_i7.Result<void>> deleteQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQueuedAction, [id]),
            returnValue: _i5.Future<_i7.Result<void>>.value(
              _i9.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteQueuedAction, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<void>>);

  @override
  _i5.Future<_i7.Result<_i12.QueuedActionModel?>> getQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedAction, [id]),
            returnValue: _i5.Future<_i7.Result<_i12.QueuedActionModel?>>.value(
              _i9.dummyValue<_i7.Result<_i12.QueuedActionModel?>>(
                this,
                Invocation.method(#getQueuedAction, [id]),
              ),
            ),
          )
          as _i5.Future<_i7.Result<_i12.QueuedActionModel?>>);

  @override
  _i5.Future<_i7.Result<List<_i12.QueuedActionModel>>>
  getAllUserQueuedAction() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserQueuedAction, []),
            returnValue:
                _i5.Future<_i7.Result<List<_i12.QueuedActionModel>>>.value(
                  _i9.dummyValue<_i7.Result<List<_i12.QueuedActionModel>>>(
                    this,
                    Invocation.method(#getAllUserQueuedAction, []),
                  ),
                ),
          )
          as _i5.Future<_i7.Result<List<_i12.QueuedActionModel>>>);
}
